on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install --only=dev
      - name: Build app
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install --only=dev
      - name: Run unit tests
        run: npm test
      - name: Coverage report
        run: npm run test:coverage
  
  build-docker-image:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag movierama-client:$(date +%s) --build-arg MOVIE_DB_API_KEY=${{ secrets.MOVIE_DB_API_KEY }}
      - name: Deploy to Netlify
        run: |
          curl -X POST -d {} -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" "https://api.netlify.com/build_hooks/6485d4f9d2a28e19f84b0d08"